### Support available at: sgrewritten.org/discord ################################ Version: ${project.version}
# +-,┌-.¸-┌─┬┬─┐-- . -- ,┬┬-.¸ - ,┌-.¸ --- ô -- ┌─┬┬─┐-·┌┬───┐---- ▄▄▄ - ‚——. -▄--▄-▄--▄-▄-▄▄▄▄▄-+ #
# | ``=ı¸   ||    /\\    ||__;  |(  __¸   /\\     ||    |├--:      █▄▄▀ (“‡‡”) █▄▄▀ █▄▄▀ █   █   | #
# | :¸_|;  ,||. ¸/¯¯)\¸ ¸||¯)\¸  \\__|; ¸/¯¯)\¸  ,||.  ,||,,,;     █▄▄█  \__/  █  █ █  █ █   █   | #
# +--------------------------------------{OFFICIAL MODULE}---------------------------------------+ #
# |                 __  __ ______ _____ _    _          _   _ _____ _____  _____                 | #
# |                |  \/  |  ____/ ____| |  | |   /\   | \ | |_   _/ ____|/ ____|                | #
# |                | \  / | |__ | |    | |__| |  /  \  |  \| | | || |    | (___                  | #
# |                | |\/| |  __|| |    |  __  | / /\ \ | . ` | | || |     \___ \                 | #
# |                | |  | | |___| |____| |  | |/ ____ \| |\  |_| || |____ ____) |                | #
# |                |_|  |_|______\_____|_|  |_/_/    \_\_| \_|_____\_____|_____/                 | #
# |______________________________________________________________________________________________| #
# |                                  sgrewritten.org/mechanics                                   | #
# +----------------------------------------------+-----------------------------------------------+ #
# |    Documentation: sgrewritten.org/infoSGM    |     Bug Reports: sgrewritten.org/bugsSGM      | #
# +----------------------------------------------+-----------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                      General Preferences                                     | #
# +----------------------------------------------------------------------------------------------+ #

# What language will this module use when communicating with your users?
# Supported languages [en].
#
# If SGM isn't yet available in your language, please consider becoming a translator:
# https://crowdin.com/project/stargate-bukkit
locale: en

# +----------------------------------------------------------------------------------------------+ #
# |                                      General Behaviour                                       | #
# +----------------------------------------------------------------------------------------------+ #
gates:
# |                                      [ Flag Toggles ]                                        | #
# |__   Some flags may be problematic in some cases, and as such, may optionally be disabled   __| #
  disabledFlags: []


# |                                  [ Generation Behaviour ]                                    | #
# |__       Configurations Needed for Stargate Mechanics G, J, & Ruined Flags/Behaviours.        | #
  generation:

    # If needed, should G gates break blocks to generate?
    agressiveGateGeneration: true

    # When a new G or J gate is generated, what behaviour should select the gateformat?
    # Options:
    #    - Origin [Duplicate the origin portal's design in the destination]
    #    - Specific [Specify a .gate file for the portal's destination's design].
    gateformatSelectionMethod: specific

    # This setting is ignored unless gateFormatSelectionMethod is set to "Specific"
    specifiedGateFormat: nether.gate

    # What flag should be on generated G portals with random coordinates?
    jumpGateDestinationFlags: 'HD{1m}'

    #What flags should be on generated G portals by default?
    generateGateDestinationFlags: ''

# |                                           [ Debug ]                                          | #
# |__     These settings are provided to help developers diagnose issues with this plugin.     __| #

# An internal value used by the plugin to determine how old your config is.
# Please do not change this.
configVersion: 3
