name: StargateMechanics
main: org.sgrewritten.stargatemechanics.StargateMechanics
version: 0.0.1
description: Command addon for the Stargate plugin for Bukkit
author: Thorinwasher
depend: [ Stargate ]
api-version: 1.18
commands:
  stargatemechanics:
    aliases:
      - sgm
      - sgmechanics
    description: The root command for stargate mechanics
    usage: |
      /<command>
permissions:
  stargate.mechanics.info:
    description: Allows the use of /sgm info
    default: op