name: StargateExtraFlags
main: net.knarcraft.stargateextraflags.StargateExtraFlags
version: 0.0.1
description: Command addon for the Stargate plugin for Bukkit
author: [EpicKnarvik97, Thorinwasher]
depend: [ Stargate ]
api-version: 1.18
commands:
  stargateflag:
    aliases:
      - sgf
    description: The root command for sgef
    usage: |
      /<command>
permissions:
  stargate.extraflags.info:
    description: Allows the use of /sgf info
    default: op